import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import { Gallery } from "@/components/Gallery";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Dongle&family=Nova+Mono&family=Orbitron:wght@500;600;700;800;900&family=Rammetto+One&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header>
        <Header />
      </header>
      <main className={styles.main}>
        <Gallery />
      </main>
    </>
  );
}
