import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import { Gallery } from "@/components/Gallery";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <Gallery />
      </main>
    </>
  );
}
